### ISSUE TITLE
Return filtering Query

### ISSUE THREAD

**Issue by AbodiSadiqGitHub** [jgithaiga/flutter_sms_inbox#13]
I want to filter query, for example:
every five second I want to select the messages that starts with 'word'.
how can i do that?

thanks in advance.

**Comment by jgithaiga** [comment]
On the current implementation, the package's query support (`querySms(...)`) is limited to `address, threadId, and kind`. You can however fetch all/some messages and filter the returned list using dart list operations.

**Comment by AbodiSadiqGitHub** [comment]
Thanks for answer, I will do like you said.
Now, I want to get sender name not phone number.
Is it possible?

**Comment by jgithaiga** [comment]
For that, please check out this package: https://pub.dev/packages/sms_advanced
