### ISSUE TITLE
Checking what SIM/Phone number received a message

### ISSUE THREAD

**Issue by williamluke4** [jgithaiga/flutter_sms_inbox#15]
Hey Julius, 
Thank you so much for creating this. 

I'm currently using this here https://github.com/williamluke4/myPesa to extract transactions from M-PESA. 

Was wondering how easy it would be to check what phone number or sim a message was sent to (i.e for multi-sim devices). I've had a brief dig around and it does not seem as trivial as I would have hoped.

**Comment by jgithaiga** [comment]
Hi @williamluke4,

**Comment by williamluke4** [comment]
Hey @jgithaiga,

I have finally had some time to have a look at this but it seems that the address returned here is the sender's address not the recipient's address.

As you can see below the following message was sent from Safaricom/MPESA to my number but the address shows MPESA, not my number.

![image](https://github.com/jgithaiga/flutter_sms_inbox/assets/10773719/b7a091d7-d9a4-48ef-843a-25a351ec9f12)

**Comment by williamluke4** [comment]
Added the subId then allowes you to look up the phone number from carrierInfo

https://github.com/jgithaiga/flutter_sms_inbox/pull/21
